<?php

namespace AppBundle\Repository;

/**
 * CodiciRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodiciRepository extends \Doctrine\ORM\EntityRepository
{
}
